# Generated by Django 5.0.4 on 2024-04-08 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100)),
                ('size_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_memo', models.CharField(max_length=100)),
                ('menu_count', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafekiosk.menu')),
                ('option_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafekiosk.option')),
                ('order_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafekiosk.ordertype')),
                ('size_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafekiosk.size')),
            ],
        ),
    ]
